### ISSUE TITLE
pylint issues

### ISSUE THREAD

**Issue by mgrajesh1** [cetcs92/module-scanner#13]
pylint issues:
setup.py:1:0: C0114: Missing module docstring (missing-module-docstring)
************* Module module_scan.scan
src/module_scan/scan.py:2:1: C0303: Trailing whitespace (trailing-whitespace)
src/module_scan/scan.py:55:0: C0301: Line too long (120/100) (line-too-long)
src/module_scan/scan.py:1:0: C0114: Missing module docstring (missing-module-docstring)
src/module_scan/scan.py:9:0: C0103: Constant name "white_space" doesn't conform to UPPER_CASE naming style (invalid-name)
src/module_scan/scan.py:10:0: C0103: Constant name "white_space_plus" doesn't conform to UPPER_CASE naming style (invalid-name)
src/module_scan/scan.py:11:0: C0103: Constant name "non_capture_beginning_of_line" doesn't conform to UPPER_CASE naming style (invalid-name)
src/module_scan/scan.py:12:0: C0103: Constant name "non_capture_import_statement" doesn't conform to UPPER_CASE naming style (invalid-name)
src/module_scan/scan.py:13:0: C0103: Constant name "capture_module_name" doesn't conform to UPPER_CASE naming style (invalid-name)
src/module_scan/scan.py:14:0: C0103: Constant name "optional_more_modules" doesn't conform to UPPER_CASE naming style (invalid-name)
src/module_scan/scan.py:17:0: C0115: Missing class docstring (missing-class-docstring)
src/module_scan/scan.py:17:0: R0205: Class 'ImportScan' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
src/module_scan/scan.py:28:4: C0116: Missing function or method docstring (missing-function-docstring)
src/module_scan/scan.py:33:4: C0116: Missing function or method docstring (missing-function-docstring)
src/module_scan/scan.py:40:4: C0116: Missing function or method docstring (missing-function-docstring)
src/module_scan/scan.py:45:13: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
src/module_scan/scan.py:48:12: W0702: No exception type(s) specified (bare-except)
src/module_scan/scan.py:76:0: C0116: Missing function or method docstring (missing-function-docstring)
src/module_scan/scan.py:77:4: C0103: Variable name "s" doesn't conform to snake_case naming style (invalid-name)

**Comment by Kapil-Kawathekar** [comment]
Hi @mgrajesh1 I want to contribute to this, can I take up this issue

**Comment by Kapil-Kawathekar** [comment]
Hi @mgrajesh1 I have fixed pylint issues and created a pull request take a look.

**Comment by mgrajesh1** [comment]
PR #14 merged
