### ISSUE TITLE
scan quietly exits if repo path doesn't exist/not readable

### ISSUE THREAD

**Issue by mgrajesh1** [cetcs92/module-scanner#16]

**Comment by Muhammadwasi** [comment]
Hi @mgrajesh1 ,

Can you please specify how can I reproduce this issue?

Thanks.

**Comment by Muhammadwasi** [comment]
@mgrajesh1, I have opened a PR for resolving the bug.

Please check it out and let me know if there is anything to improve.

**Comment by Muhammadwasi** [comment]
#17

**Comment by mgrajesh1** [comment]
Issue fixed, thank you
